// ===== HCII Deck · Single Source of Truth =====
// This file is loaded by index.html, presenter.html, and vocab.html.
// Update scripts here → all three sites reflect the change on next deploy.
//
// Fields: n (slide number), t (title), time (duration), en (English), zh (Chinese)

const SCRIPTS = [
  {n:1, t:"Title · 開場", time:"0:30",
   en:"Good morning. I'm Chieh-An from National Taiwan University of Science and Technology. Today I'd like to share with you the work I did with Prof. Tang on AI personas.",
   zh:"大家好。我是來自台灣科技大學的簡潔安。今天要跟大家分享我跟唐玄輝教授一起做的 AI 人物誌研究。"},
  {n:2, t:"Background · 背景與缺口", time:"1:00",
   en:"With Generative AI, personas have become interactive agents you can actually talk to. Most existing work has asked 'how human-like is the AI?' But how AI personas differ from real participants still remains unclear. We looked at this question from a different angle. We wanted to know what value this difference brings, and how it changes the way we do design research.",
   zh:"有了生成式 AI，人物誌變成可以對話的代理人。過去多數研究都在問「AI 像不像真人」，但 AI 人物誌跟真人之間的差異到底是什麼，目前還不清楚。我們從另一個角度切入，想知道這個差異本身有什麼價值、會如何改變我們做設計研究的方式。"},
  {n:3, t:"Research Questions · 研究問題", time:"0:45",
   en:"So we asked two questions. First, how to build an AI persona that stays consistent and is clearly different from other personas? Second, what are the structural differences in language between AI personas and real people?",
   zh:"我們問了兩個問題。第一，怎麼建構一個一致、可區辨的 AI 人物誌？第二，AI 人物誌跟真人在語言表現上有哪些結構性差異？"},
  {n:4, t:"Method · Research Process · 研究流程", time:"0:30",
   en:"We built our AI persona using Design Science Research. We treated the AI persona as an artifact: we build it, then we evaluated it across two studies that were designed to answer our two RQs.",
   zh:"我們用設計科學研究方法建構 AI 人物誌。把它當成一個人造物：先建構出來，再用兩個對應我們兩個 RQ 的研究去評估它。"},
  {n:5, t:"Method · Context · 研究情境", time:"1:00",
   en:"To test whether a script can keep a persona stable, we needed two opposing personas that live inside the same real-world context. Taiwan's Gen Z ETF market gave us exactly that. It's a fast-growing market with real commercial weight, and inside it we can see two clearly opposing types — one who trusts the crowd, and one who trusts her own rules. That contrast lets us build two personas whose differences are grounded in real behavior, not just in labels.",
   zh:"為了測試劇本能不能撐出一個穩定的 Persona，我們需要在同一個真實情境裡找到兩種對立的角色。台灣 Z 世代 ETF 這個市場剛好符合。這是一個規模夠大、還在快速成長的市場，具有實際的商業份量。而且在這裡我們可以看到兩種鮮明對立的類型——一種相信社群、一種相信自己的紀律。這樣的對比讓我們能建構出行為差異真實存在的兩位角色，而不只是貼標籤。"},
  {n:6, t:"Method · Construct · 建構流程", time:"1:00",
   en:"We built the persona in four stages. In the first stage, we used Gemini Deep Research to identify two core axes and four user types, and then build a full profile for each quadrant. Second, to train our personas, we used ChatGPT Deep Research to pull thirty to fifty posts of a first-person voice from Taiwanese online forums. That is where the persona's voice comes from. Third, we wrote a six-dimension script for the personas. Finally, we shipped the script as a GPT with five behavior constraints and role-internalization instructions, so the persona stays in character through long conversations.",
   zh:"我們分四階段建角色。第一階段，建立脈絡：用 Gemini Deep Research 找出兩條核心軸線跟四種用戶類型，再把十字象限四個類型完整刻劃出來。第二階段，語料蒐集：用 ChatGPT Deep Research 從台灣論壇 PTT、Dcard 抓 30 到 50 則第一人稱貼文，角色的聲音來自這裡。第三階段，劇本生成：寫出六維度劇本。第四階段，部署：把劇本上 GPT，加上 5 條行為限制跟角色內化指令，讓角色在長對話中不脫線。"},
  {n:7, t:"Six Dimensions · 六維度", time:"1:00",
   en:"For the script, we considered six dimensions. Basic information anchors the identity of the persona, which is a she. Worldview shapes how she sees the market, money, and the future. Psychological state captures what makes her anxious and where her confidence comes from. Behavior covers her daily rituals, like checking the app or chatting with friends. Linguistic style locks in the things that make her sound like herself: slang, particles, tempo. And daily scenarios put her into real situations like commute, payday, or a market crash. Together, these six dimensions hold one stable character across hundreds of turns.",
   zh:"劇本有六個維度。基本資料負責錨定角色身份，這個角色是一位女性，包含年齡、職業、人生階段。世界觀形塑她怎麼看市場、金錢、未來。心理狀態抓住她在焦慮什麼、信心從哪裡來。行為模式涵蓋她每天的習慣，像是刷盤、找朋友聊天。語言風格鎖住「一聽就知道是她」的東西，俚語、語助詞、節奏。日常情境把她放進真實場景，像通勤、發薪日、市場崩盤。六個維度一起撐住一個穩定的角色，撐過上百回合對話。"},
  {n:8, t:"Script Sample · 劇本實例", time:"0:30",
   en:"Here is what the script actually looks like — a live screen recording of the GPT system prompt for each persona. Same six dimensions, written in Traditional Chinese, but the content is intentionally opposite. Let's see how that plays out.",
   zh:"這就是劇本真正的樣子 — 兩位角色各自的 GPT 後台螢幕錄影。同樣的六維度結構、繁體中文撰寫，但內容刻意對立。接下來看看這對立如何呈現。"},
  {n:9, t:"Two Personas · Anne & Emily", time:"0:45",
   en:"Same six-dimension script, but we flip one axis, source of confidence, and we get two opposite personas. Take a look at how they answer the same question. Ann's decisions, quote unquote, get pulled along by social platforms. When PTT or her friends are talking about a stock, she follows. Her must-haves are price alerts and trending rankings, because she wants to react fast. On the other hand, Emily, quote unquote, doesn't watch news or YouTube. Her decisions rest on her own principles. Her must-haves are automated recurring investments and rebalancing, because she wants the app to help her stay the course. Same question, completely different answers.",
   zh:"我們建了兩個對立的角色，只翻轉一條軸線——信心來源——其他都相同。大家可以看一下她們對同樣問題的回答。小安的決定，引用她原話，「被社群平台帶著走」。PTT 跟朋友在講什麼，她就想跟。她的必備功能是價格警示跟熱門排行，因為她想趕快反應。另一方面，艾蜜莉，引用她原話，「不看新聞跟 YouTube」。她的決定建立在自己的原則上。她的必備功能是定期定額跟再平衡，因為她要 app 幫她守紀律。同樣的問題，完全不同的答案。"},
  {n:10, t:"Study 1 · Design · 研究一設計", time:"1:00",
   en:"To answer RQ1, the consistency question, we ran Study 1. We invited six senior designers, each with three or more years of UX research experience. None of them were involved in building the persona, so they could evaluate it objectively. Every session had three parts. First, a stability test: three rounds with each persona using six interview questions, rated on a five-point scale from completely inconsistent to completely consistent. Second, a discriminability test: comparing Anne and Emily head-to-head on each question, rating whether their answers felt identical or very different. Third, separately, the Persona Perception Scale from Salminen and colleagues, which rates six perception constructs for both personas on a one-to-seven Likert scale.",
   zh:"為了回答 RQ1 一致性的問題，我們做了研究一。我們邀請了六位資深設計師，都是有三年以上 UX 研究經驗的人。他們沒有參與人物誌的建構，所以可以客觀評估。流程分三個部分，都在同一場進行。第一，穩定性測試：跟兩位角色各進行三輪對話，用六道訪談題，1 到 5 分量表評分，1 是完全不一致、5 是完全一致。第二，差異性測試：對每一題比對小安跟艾蜜莉的回答，1 到 5 分評兩位回答有多相像或多不同。第三，另外搭配人物誌感知量表，這是 Salminen 等人 2020 年發展的，兩位都填，用 1 到 7 分量表評六個感知面向。"},
  {n:11, t:"Study 1 · Results · 研究一結果", time:"1:15",
   en:"Now for the results. Let us first look at the chart on the left, which shows the scores from the stability test and the discriminability test. Both personas held stable — Anne at 4.17 and Emily at 4.47 out of 5. And the two had a clear distinction, shown by 4.58 out of 5. On the right we have the Persona Perception Scale. The first five constructs all had a higher-than-random mean for both personas. This shows that they are indeed useful — Anne's overall is 4.76 and Emily's is 4.86. On the other hand, credibility had the lowest mean for both — Anne 3.67 and Emily 4.17. This reflects that the evaluators could clearly distinguish AI from real people, and were aware of the nature of the tool.",
   zh:"結果這樣。小安一致性 4.17、艾蜜莉一致性 4.47，兩位都穩。兩角色差異性 4.58、清楚可辨。感知量表前五個構面兩位都高於中間值，整體上小安 4.76、艾蜜莉 4.86，都堪用。可信度兩位都是最低 — 小安 3.67、艾蜜莉 4.17。這正反映了一個邊界：評估者能清楚辨識 AI 與真人的差異，顯示設計師對工具本質保有批判意識。"},
  {n:12, t:"Study 2 · Design · 研究二設計", time:"1:00",
   en:"For RQ2, which is to investigate language differences between AI and humans, we ran a simulation-validation interview online. We interviewed Anne and two screened humans, aged 24 and 26, both matching Anne's Gen Z emotional profile. Each session was 60 minutes. The interview was built around three design concepts, all addressing the same brief: when market volatility triggers panic, how do we stabilize emotional investors so they don't deviate from their plan. For every concept, we asked these same four questions on the middle of the slide. We then coded each response on six linguistic dimensions on the right, each capturing one aspect of how the person talks and thinks, on a 1 to 5 Likert scale. I will walk through the most striking dimensions with examples in the next slide.",
   zh:"為了回答 RQ2 的語言差異問題，我們做了「模擬驗證訪談」，全程線上進行。受訪者是 AI 小安加上兩位篩選過的真人，24 跟 26 歲，都符合小安的 Z 世代情緒型投資者側寫。每場 60 分鐘。訪談圍繞三個設計方案進行，這三個方案都在回應同一個設計題目：當市場波動引發恐慌時，怎麼穩定情緒型投資者、讓她們不偏離投資計畫。每個方案我都問同樣的四道題，就是簡報中間這四題。回應用右邊的六個語言維度編碼，每個維度抓的是「一個人怎麼說、怎麼想」的一個面向，1 到 5 分打分。下一頁我會用例子帶大家看最關鍵的兩個維度。"},
  {n:13, t:"Study 2 · Results · 研究二結果", time:"1:30",
   en:"Two dimensions tell the story. Variability reveals that real humans drop hundreds of hesitation markers per interview — fillers, restarts, broken sentences. The AI dropped zero but used emojis, showing that its language was more polished. Tempo reveals that real reflections takes about four minutes to surface; this is because it has to be constructed. The AI gives reflections instantly, at zero delay. Across all six dimensions, AI is plus-43% structural but minus-79% authenticity. The structural fluency actually reveals a lack in authenticity.",
   zh:"兩個維度就把整個故事說完了。C2 變化程度：真人每場訪談會冒出幾百個語氣詞跟遲疑——口頭禪、自我修正、句子破碎。AI 一個都沒有，改用 emoji 補位。太乾淨，反而露餡。C6 思考節奏：真人的反思大約要四分鐘才浮現，因為那是邊講邊建構的。AI 則是問完立刻給答案，零延遲。六個維度合起來看，AI 的結構性比真人高 43%、真實性比真人低 79%。讓 AI 看起來很流暢的那份完整，其實正好凸顯了真實性的差距。"},
  {n:14, t:"Findings · Two Modes · 兩種思考", time:"1:10",
   en:"The main takeaway from the two studies above is that AI and humans demonstrate different ways to organize thoughts. The AI shows what we call synthetic thinking. The answer is already there before the question finishes, with zero delay and only three interaction markers. The humans show experiential thinking. The answer forms while they are speaking, with 45 interaction markers, and the real reflection often surfaces only about four minutes later.",
   zh:"這兩個研究最主要的啟示是：AI 跟真人展現出兩種不同的思考組織方式。AI 是所謂的「合成式思考」——答案在問題還沒講完之前就已經成形了，零延遲、只出現三個互動標記。真人則是「經歷中的思考」——答案是邊講邊長出來的，一場訪談有 45 個互動標記，而且真正的反思常常要四分鐘後才浮現。"},
  {n:15, t:"Discussion · Baseline · 對照基準", time:"1:15",
   en:"So the AI's real value is not in simulating humans but in revealing something that deserves more attention in human interviews. Human interviews bring out what AI cannot: hesitation, contradiction, and emotion. When compared to AI's fluent responses, these interaction markers become meaningful cues instead of noise, inviting us as interviewers to probe deeper (Smith, 2012). AI personas are efficient and always available, so they are perfect for exploring the problem space, finding patterns, and giving designers something solid to compare against in the early stage of research. AI and humans should be complementary, not competing. Different tools serve different jobs: AI for breadth early on, humans for depth later on.",
   zh:"所以 AI 真正的價值不在於模擬真人，而在於讓真人訪談中值得被更多關注的東西被看見。真人訪談帶來 AI 給不了的：遲疑、矛盾、情緒。跟 AI 流暢的回應相比，這些互動痕跡就從雜訊變成有意義的線索，提示我們身為訪談者可以再往深處探（Smith, 2012）。AI 人物誌效率高、隨時可用，所以適合研究的前期：探索問題空間、找模式，讓設計師有個明確的東西可以對照。AI 跟真人應該是互補的，不是競爭。不同工具負責不同任務：AI 適合前期廣度，真人適合後期深度。"},
  {n:16, t:"Living System · 活系統 & 貢獻", time:"1:30",
   en:"To wrap up, this study makes three contributions. Methodologically, we built a validated six-dimension framework for building AI personas. Conceptually, we revealed a distinction between synthetic and experiential thinking, and suggested we look beyond just measuring fidelity. And practically, we showed a clear positioning of how to use AI and humans together: AI for breadth, humans for depth. This points to what we call a living system. The persona evolves, based on real-world data — designer interview records and CRM data from real users.",
   zh:"最後總結，這份研究做出三個貢獻。方法上，我們建構出一套經過驗證的六維度框架，用來建構 AI 人物誌。概念上，我們揭示了合成式思考跟經歷中思考的區分，並主張這個領域可以看得比「擬真度」更遠。實務上，我們提出 AI 與真人協作的明確定位：AI 廣度、真人深度。這指向一個我們稱為「活系統」的方向。人物誌會不斷演化，基於真實世界的資料——設計師的訪談紀錄，以及來自真實使用者的 CRM 資料。"},
  {n:17, t:"Conclusion · 結論", time:"0:20",
   en:"From static snapshot to a living system. AI personas do not replace humans. They complement them. And once consistent, they can keep growing with continuous data.",
   zh:"從靜態快照到活系統。AI 人物誌不取代真人，而是與真人互補。一旦一致，就能透過持續的資料成長下去。"},
  {n:18, t:"Thank You · 致謝", time:"0:15",
   en:"Thank you. I would love to take your questions.",
   zh:"謝謝聆聽，很歡迎提問。"},
];

// Q&A backup slides (only visible in main deck's Q&A section, not in presenter/vocab)
const QA_SCRIPTS = [
  {n:19, t:"Q&A · Q1 · Sample Size", time:"Q&A",
   en:"Q: \"You had only six evaluators in Study 1 and two human participants in Study 2. Isn't your sample too small to draw conclusions?\" — Lead: \"You are right that the sample is small.\" Then: (1) Reframe as exploratory methodology-development. (2) Evidence: 79% gap is too large to ignore. (3) Future: starting point of a research program, will scale up.",
   zh:"問題：「樣本是不是太小？」— 開頭句：「您說得對，樣本確實小。」然後：(1) 重新定位為探索性研究 (2) 反駁：79% 差距太大 (3) 未來會擴大樣本。"},
  {n:20, t:"Q&A · Q2 · Single Coder", time:"Q&A",
   en:"Q: \"You were the only coder. Without inter-rater reliability, how do we know these scores aren't subjective?\" — Lead: \"That is a fair concern.\" Then: (1) Counter: each dimension has quantifiable indicators (count markers, time delay) — scores grounded in observable signals. (2) Future: second coder + IRR planned.",
   zh:"問題：「沒有跨編碼者信度，會不會是你主觀詮釋？」— 開頭句：「這是合理的質疑。」然後：(1) 每個維度都有可量化指標 (2) 未來會加第二編碼者跟 IRR。"},
  {n:21, t:"Q&A · Q3 · Generalizability", time:"Q&A",
   en:"Q: \"How does the method generalize to other domains?\" — Lead: \"We chose this context specifically because of its strong emotional-behavioral coupling.\" Then: (1) Method (six-dimension script) is domain-agnostic. (2) Framework applies to any user group; content needs re-grounding. (3) Gen Z ETF is test bed, not limit.",
   zh:"問題：「方法在其他領域通用嗎？」— 開頭句：「我們選這情境是因為它情緒行為連動最強。」然後：(1) 方法本身不限領域 (2) 框架可套用但內容要重新建構 (3) Z 世代 ETF 是測試場域不是上限。"},
  {n:22, t:"Q&A · Q4 · Why Not Make AI More Human-Like", time:"Q&A",
   en:"Q: \"If AI is too perfect, shouldn't future work make AI better mimic humans?\" — Lead: \"That is exactly the question we deliberately moved away from.\" Then: (1) Most work tries to make AI more human-like. (2) Mimic surface ≠ experience cognition. (3) More useful position: AI as structural baseline. This is division of labor, not competition.",
   zh:"問題：「為什麼不讓 AI 更像真人？」— 開頭句：「這正是我們刻意不走的方向。」然後：(1) 多數研究在讓 AI 更像真人 (2) 模仿表面 ≠ 經歷認知 (3) 更有用的定位是當對照基準。不是競爭，是分工。"},
  {n:23, t:"Q&A · Q5 · Workflow Integration", time:"Q&A",
   en:"Q: \"How does AI baseline integrate into the workflow in practice?\" — Lead: \"In our recommended workflow, the AI persona comes first.\" Then: (1) AI early stage: explore problem space, get structured baseline. (2) Humans later: direct comparison. (3) Hesitation/contradiction/emotion become signals, not noise. In short: AI for breadth, humans for depth.",
   zh:"問題：「實務上怎麼整合 AI 跟真人訪談？」— 開頭句：「我們建議的流程是 AI 人物誌先上。」然後：(1) AI 前期：探索 + 給基準 (2) 真人後期：直接對照 (3) 遲疑/矛盾/情緒變成訊號。簡單講：AI 廣度、真人深度。"},
  {n:24, t:"Q&A · Universal Answer Techniques", time:"Q&A",
   en:"5 frameworks for any question: (1) Acknowledge & Pivot — \"Thank you for that question. It's an important point.\" (2) Restate to Clarify — \"If I understand correctly, you're asking whether X.\" (3) Honest Limit + Future — \"You're right, that's a real limitation.\" (4) Anchor to Concrete — \"Let me give a concrete example from our data.\" (5) Yes-and, not Yes-but. Bonus: Pause Power — silence is OK, pause 2-3 seconds before answering hard questions.",
   zh:"5 個萬用框架：(1) 緩衝橋接 (2) 重述確認 (3) 承認侷限 + 拋未來 (4) 拉回具體案例 (5) Yes-and 不 Yes-but。Bonus：沉默是金，停 2-3 秒再開口。"},
];

// Combined array with all 24 slides (used by index.html)
const ALL_SCRIPTS = SCRIPTS.concat(QA_SCRIPTS);
